name=EasyIno
version=0.1.0
author=Rafael
maintainer=Rafael
sentence=The simplest bridge between Python and Arduino.
paragraph=EasyIno allows you to register variables and commands on the Arduino and access them directly from Python using JSON over Serial.
category=Communication
url=https://github.com/Faelzin09663/easyINO
architectures=*
depends=ArduinoJson
